project_id = "rkucenozpmaixfphpiub"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
smtp_port = 54327

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"

[auth.external.facebook]
enabled = true
client_id = "env(FACEBOOK_CLIENT_ID)"
secret = "env(FACEBOOK_CLIENT_SECRET)"

[edge_runtime]
enabled = true
policy = "oneshot"

[functions.chat-ai]
verify_jwt = false

[functions.klarna-payment]
verify_jwt = true

[functions.document-analyzer]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.notify-admin-kitchen-partner]
verify_jwt = false

[functions.reset-chef-password]
verify_jwt = true

[functions.approve-chef-create-account]
verify_jwt = true

[functions.phone-ai-token]
verify_jwt = false

[functions.swish-payment]
verify_jwt = false

[functions.swish-callback]
verify_jwt = false

[functions.approve-restaurant-create-account]
verify_jwt = true

[functions.notify-admin-application]
verify_jwt = true

[functions.send-application-notification]
verify_jwt = false

[functions.send-business-confirmation]
verify_jwt = false

[functions.notify-admin-business-application]
verify_jwt = false

[functions.send-business-decision]
verify_jwt = false
